version: "3.8"

services:
  db:
    image: mysql:8
    container_name: ${MYSQL_HOST}
    volumes:
      - ./database/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}

  backend:
    image: node:18-alpine
    container_name: nest-api
    links:
      - db:${MYSQL_HOST}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    tty: true
    env_file: .env
